shared:
    image: node:6
jobs:
    main:
        steps:
            - user-pwd: pwd
            - teardown-step: pwd
            - meta-set: meta set foo '{"bar": "baz", "buz": 123}' --json-value
            - meta-get: meta get foo --json-value
        requires: [~pr, ~commit]
    external:
        steps:
            - meta: meta get foo --external sd@726:test
            - env: env
        requires: [~pr, ~sd@726:test]
