shared:
  image: node:6
jobs:
  main:
    steps:
      - metaset: meta set hello bye
      - runstep: APP=sdapi && eval "$STATUS"
      - echo: echo $SD_TOKEN
    requires:
      - ~commit
      - ~pr
    environment:
      STATUS: echo $APP
