shared:
  image: node:6
jobs:
  main:
    steps:
      - set-unstable: |
          if [ "$COVERAGE" -lt 95 ]
            then curl -X PUT -H "Authorization: Bearer $SD_TOKEN" -H "Content-Type: application/json" -d '{"status": "UNSTABLE", "statusMessage": "this build is unstable"}' "${API_URL}/${SD_BUILD_ID}"
          fi
    environment:
        COVERAGE: 90
        API_URL: https://api.screwdriver.cd/builds
    requires:
      - ~commit
