shared:
  image: node:6
jobs:
  main:
    steps:
      - echo: echo $SD_TOKEN
      - metaset: meta set foo 123456789
      - metaget: meta get foo
    requires:
      - ~commit
      - ~pr
    environment:
      STATUS: echo $APP
  test:
    steps:
      - getstuff: meta get foo
    requires:
      - main
