shared:
  image: node:6
jobs:
  main:
    steps:
      - set: export COVERAGE=90
      - unstable: |
          if [ "$COVERAGE" -lt 95 ]
            then curl -X PUT -H "Authorization: Bearer $API_TOKEN" -H "Content-Type: application/json" -d '{"status": "UNSTABLE", "statusMessage": "this build is unstable"}' $API_URL/$SD_BUILD_ID
          fi
    environment:
      API_URL: https://api.screwdriver.cd/v4/builds
    secrets:
      - API_TOKEN
    requires:
      - ~commit
