shared:
  image: node:6
jobs:
  main:
    steps:
      - echo: echo "This build status is set as Unstable and will not trigger the next build"
    environment:
        COVERAGE: 90
        API_URL: https://api.screwdriver.cd/v4/builds
    requires:
      - ~commit
  publish:
    steps:
      - echo: echo "This will not be triggered"
    requires:
      - main
