shared:
  image: node:6
jobs:
  main:
    steps:
      - metaset: meta set hello bye
      - sleep: sleep 1000
    requires:
      - ~commit
      - ~pr
  prJob4444:
    steps:
      - newstep: echo bye
      - newerstep: echo bye
    requires:
      - ~pr
  prJob8888:
    steps:
      - echo22: echo hello
    requires:
      - ~pr
