shared:
    image: node:6
jobs:
    main:
        steps:
            - write: echo hello
            - env: env
#        sourcePaths: ["screwdriver.yaml"]
        requires: [~pr, ~commit]
        environment:
            test: 'abc'
