shared:
    image: node:6
jobs:
    main:
        steps:
            - user-pwd: pwd
            - meta-set-1: meta set foo.bar baz
            - meta-get-1: meta get foo --json-value
#            - meta-set-2: meta set foo '{"bar": "baz", "buz": 123}' --json-value
        requires: [~pr, ~commit]
    external:
        steps:
            - meta: meta get foo --external sd@726:test
            - env: env
        requires: [~pr, ~sd@726:test]
