shared:
  image: node:6
jobs:
  prJob4444:
    steps:
      - newwwwwww: echo bye
      - newerstep: echo bye
    requires:
      - ~pr
  prJob10000:
    steps:
      - echo22: echo hello
    requires:
      - ~pr
