shared:
  image: node:6
jobs:
  main:
    steps:
      - metaset: meta set hello bye
      - sleep: sleep 1000
    annotations:
      beta.screwdriver.cd/cpu: HIGH
      beta.screwdriver.cd/ram: LOW
    requires:
      - ~commit
      - ~pr
  main2:
    steps:
      - echo: echo bye
    requires:
      - ~pr
  newPR:
    steps:
      - byebye: echo hello
    requires:
      - ~pr
