jobs:
 A:
  requires: [~commit]
  image: node:6
  steps:
    - logs: echo $SD_TOKEN
    - sleep: sleep 100
 B:
  requires: []
  image: node:6
  steps:
    - a: echo "a"
 C:
  requires: [A, B]
  image: node:6
  steps:
  - b: echo "sample"
