shared:
    image: node:6
jobs:
    main:
        # template: tifftemplate2@1.3.1
        steps:
            - stuff: echo $SD_TOKEN
            - eventid: echo $SD_EVENT_ID
            - evn: printenv
            - preecho: echo 'I am adding this'
            - echo: echo 'replacing this step'
            - postecho: echo 'bye bye' > /tmp/config
        requires: ~commit
    sd-setup-scm:
        requires: main
        steps:
            - echostuff: echo bye
