shared:
    image: node:6
jobs:
    main:
        steps:
            - pwd: pwd
            - teardown-step: pwd
        requires: [~pr, ~commit]
    external:
        steps:
            - meta: meta get foo --external sd@726:test
            - env: env
        requires: [~pr, ~sd@726:test]
