shared:
  image: node:6
jobs:
  main:
    steps:
      - metaget3: meta get nonexist
      - metaset: meta set foo barrrrrr
      - metaget: meta get foo
      - metaget2: meta get stuff
    annotations:
      beta.screwdriver.cd/cpu: HIGH
      beta.screwdriver.cd/ram: LOW
