shared:
    image: node:6
jobs:
    main:
        steps:
#            - build: echo $SD_TOKEN
            - meta-set: meta set foo barbar
            - meta-get: meta get foo
            - sleep: sleep 10
            - exit: fail fail
#            - name: stuff
#              command: echo "hello"
#              alwaysRun: true
            - what: echo "bye"
    third:
        steps:
            - meta-get2: meta get foo
