shared:
    image: node:6
jobs:
    main:
        steps:
            - env: env
            - set: export SD_ARTIFACTS_DIR=/tmp
            - get: echo $SD_ARTIFACTS_DIR
        requires: [~pr, ~commit]
