shared:
    image: node:6
jobs:
    main:
        steps:
#            - build: echo $SD_TOKEN
            - meta-set: meta set foo barbar
            - meta-get: meta get foo
            - exit 1
            - name: stuff
              command: echo "hell"
              alwaysRun: true
    third:
        steps:
            - meta-get2: meta get foo
