shared:
    image: node:6
jobs:
    main:
        steps:
            - write: echo hello > /tmp/test
            - cp: cp /tmp/test $ARTIFACTS_DIR
        sourcePaths: ["screwdriver.yaml"]
        requires: [~pr, ~commit]
