shared:
    image: node:6
jobs:
    main:
        steps:
            - env: env
            - pr: if [ "$SD_PULL_REQUEST" = "" ]; then echo "not pull request";  else echo "is a pull request"; fi;
        requires: [~pr, ~commit]
    external:
        steps:
            - env: env
        requires: [~pr, ~sd@726:test]
