shared:
  image: node:6
jobs:
  main:
    steps:
      - metaset: meta set hello bye
    annotations:
      beta.screwdriver.cd/cpu: HIGH
      beta.screwdriver.cd/ram: LOW
    requires:
      - ~commit
      - ~pr
  main2:
    steps:
      - echo: bye
    requires:
      - main
