shared:
  image: node:6
jobs:
  main:
    steps:
      - echo: echo $SD_TOKEN
      - metaset: meta set foo 123456789
      - metaset: meta set test 1234
      - metaget: meta get foo
    requires:
      - ~commit
      - ~pr
    environment:
      STATUS: echo $APP
  test1234:
    steps:
      - getstuff1234: meta get foo
      - metaset: meta set foo bar
      - metaset: meta set bar baz
    requires:
      - main
